apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-ssl-protocols: "TLSv1.1 TLSv1.2"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    {{ if eq .Values.ingress.cert "" }}
    cert-manager.io/cluster-issuer: letsencrypt-cf-prod
    {{ end }}
spec:
  tls:
    - hosts:
        - {{ .Release.Name }}.k3s.brokencrystals.nexploit.app
      secretName: {{ if eq .Values.ingress.cert "" }}distributorwildcard{{ else }}{{ .Values.ingress.cert }}{{ end }}
  rules:
    - host: {{ .Release.Name }}.k3s.brokencrystals.nexploit.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: 80
