---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "brokencrystals.fullname" . }}-keycloak-prod
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "brokencrystals.fullname" . }}-keycloak-prod
spec:
  selector:
    matchLabels:
      app: {{ include "brokencrystals.fullname" . }}-keycloak-prod
  template:
    metadata:
      labels:
        app: {{ include "brokencrystals.fullname" . }}-keycloak-prod
    spec:
      containers:
        - name: {{ include "brokencrystals.fullname" . }}-keycloak-prod
          image: jboss/keycloak:latest
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
          livenessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 30

          env:
            - name: DB_VENDOR
              value: "POSTGRES"
            - name: DB_ADDR
              value: "{{ include "brokencrystals.fullname" . }}-keycloak-postgres-prod-service"
            - name: DB_DATABASE
              value: "keycloak"
            - name: DB_SCHEMA
              value: "public"
            - name: DB_PASSWORD
              value: "password"
            - name: KEYCLOAK_USER
              value: "admin"
            - name: KEYCLOAK_PASSWORD
              value: "Pa55w0rd"
            - name: KEYCLOAK_IMPORT
              value: "/opt/jboss/keycloak/imports/realm-export.json -Dkeycloak.profile.feature.upload_scripts=enabled"
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
            - name: KEYCLOAK_FRONTEND_URL
              value: "https://auth{{ .Values.ingress.authlevel }}{{ .Values.ingress.url }}/auth/"

          volumeMounts:
          - name: {{ include "brokencrystals.fullname" . }}-keycloak
            mountPath: /opt/jboss/keycloak/imports/realm-export.json
            subPath: realm-export.json
            readOnly: true

      volumes:
      - name: {{ include "brokencrystals.fullname" . }}-keycloak
        configMap:
          name: {{ include "brokencrystals.fullname" . }}-keycloak
---
kind: Service
apiVersion: v1
metadata:
  name: {{ include "brokencrystals.fullname" . }}-keycloak-prod-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ include "brokencrystals.fullname" . }}-keycloak-prod
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080

