xxe-lab:
  deployments:
    - name: attackerserver
      image: brightsec/python-xxe:attackerserver
      port: 8888

    - name: aws-metadata
      image: brightsec/python-xxe:aws-metadata
      port: 8111

    - name: vulnserver
      image: brightsec/python-xxe:vulnserver
      port: 5000
      args: ["/setup-aws-simulator.sh && python app.py"]

  services:
    - name: attackerserver
      port: 8888
      targetPort: 8888

    - name: aws-metadata
      port: 8111
      targetPort: 8111

    - name: vulnserver
      port: 5000
      targetPort: 5000

  ingresses:
    - name: attackerserver
      port: 8888

    - name: aws-metadata
      port: 8111

    - name: vulnserver
      port: 5000
