simple-service:
  application:
    image: ghcr.io/neuralegion/target2-app:latest
    port: 5000
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 512Mi
    livenessProbe:
      httpGet:
        path: /
        port: 5000
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 30
    startupProbe:
      httpGet:
        path: /
        port: 5000
        scheme: HTTP
