---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: {{ .Release.Name }}
    spec:
      restartPolicy: Always
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "pixidb"
      containers:
        - name: {{ .Chart.Name }}
          image: brightsec/pixi
          # command: ["/bin/sh"]
          # args:
          #   - -c
          #   - |
          #     sed -i 's/mongodb:\/\/pixidb:27017\/Pixidb/mongodb:\/\/localhost:27017\/Pixidb/g' ./server.js
          #  # this might be needed if we are to make helm chart for this app.
          ports:
          - name: port8000
            containerPort: 8000
          - name: api
            containerPort: 8090
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 30

        - name: {{ .Chart.Name }}-mongo
          image: deadrobots/pixi:datastore
          ports:
          - containerPort: 27017
          resources:
            requests:
              cpu: 25m
              memory: 256Mi
            limits:
              cpu: 100m
              memory: 512Mi
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 60
            periodSeconds: 30


