simple-service:
  application:
    image: "bkimminich/juice-shop:v12.0.0"
    port: 3000
    env:
      example1: foo
      example2: pass
    resources:
      requests:
        cpu: 256m
        memory: 750Mi
      limits:
        memory: 1024Mi
      ephemeral-storage: "4Gi"
