apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "crapi.fullname" . }}-{{ .Values.web.config.name }}
  labels:
    release: {{ .Release.Name }}
    {{- toYaml .Values.web.config.labels | nindent 4 }}
data:
  COMMUNITY_SERVICE: {{ include "crapi.fullname" . }}-{{ .Values.community.service.name }}:{{ .Values.community.port }}
  IDENTITY_SERVICE: {{ include "crapi.fullname" . }}-{{ .Values.identity.service.name }}:{{ .Values.identity.port }}
  WORKSHOP_SERVICE: {{ include "crapi.fullname" . }}-{{ .Values.workshop.service.name }}:{{ .Values.workshop.port }}
