apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "crapi.fullname" . }}-{{ .Values.web.name }}
  labels:
    release: {{ .Release.Name }}
    {{- toYaml .Values.web.deploymentLabels | nindent 4 }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      {{- with .Values.web.deploymentSelectorMatchLabels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
        {{- toYaml .Values.web.podLabels | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.web.name }}
          image: {{ .Values.web.image }}:{{ .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: 80
          {{- if .Values.web.resources }}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "crapi.fullname" . }}-{{ .Values.web.config.name }}
