---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dvwa.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: dvwa
spec:
  selector:
    matchLabels:
      app: dvwa
  template:
    metadata:
      labels:
        app: dvwa
    spec:
      containers:
        - name: dwva-app
          image: hightechsec/docker-dvwa
          resources:
            requests:
              cpu: 256m
              memory: 750Mi
            limits:
              cpu: 1
              memory: 1024Mi
              ephemeral-storage: "4Gi"
          livenessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 30

---
kind: Service
apiVersion: v1
metadata:
  name: {{ include "dvwa.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: dvwa
  ports:
    - port: 80