---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - "target.local"
      initContainers:
        - name: setup-iptables
          image: 454884832027.dkr.ecr.us-east-1.amazonaws.com/docker-hub-cache/library/ubuntu
          command: ["sh", "-c", "apt-get update && apt-get install -y iptables && iptables -t nat -A OUTPUT -p tcp -d 169.254.169.254 -j DNAT --to-destination 127.0.0.1:8085"]
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
            privileged: true
      containers:
        - name: metadata-mock
          image: 454884832027.dkr.ecr.us-east-1.amazonaws.com/imds-mock:latest
          ports:
          - containerPort: 80
        - name: app
          image: {{ .Values.application.image }}
          envFrom:
          - configMapRef:
              name: {{ .Release.Name }}
          resources:
{{ toYaml .Values.application.resources | indent 12 }}
          livenessProbe:
{{ toYaml .Values.application.livenessProbe | indent 12 }}
          readinessProbe:
{{ toYaml .Values.application.readinessProbe | indent 12 }}
        {{- if and .Values.global.repeaterIDs .Values.global.token .Values.global.cluster }}
        {{- range $index, $repeaterID := .Values.global.repeaterIDs }}
        - name: repeater-{{ $index }}
          image: brightsec/cli{{ if $.Values.global.repeaterImageTag }}:{{ $.Values.global.repeaterImageTag }}{{ else }}:latest{{ end }}
          command: ["bright-cli", "repeater"]
          args:
            - "--token=$(TOKEN)"
            - "--id=$(REPEATER_ID)"
            - "--cluster=$(CLUSTER)"
            - "--timeout=$(TIMEOUT)"
            - "--log-level=verbose"
          resources:
            requests:
              cpu: 200m
              memory: 100Mi
          env:
            - name: REPEATER_ID
              value: "{{ $repeaterID }}"
            - name: TOKEN
              value: "{{ $.Values.global.token }}"
            - name: CLUSTER
              value: "{{ $.Values.global.cluster }}"
            - name: TIMEOUT
              value: "{{ $.Values.global.timeout | default "30000" }}"
        {{- end }}
        {{- end }}
      imagePullSecrets:
        - name: pull-ghcr-io
