xxe-lab:
  deployments:
    - name: attackerserver
      image: brightsec/java-xxe:attackerserver
      port: 8888

    - name: aws-metadata
      image: brightsec/java-xxe:aws-metadata
      port: 8111

    - name: vulnserver
      image: brightsec/java-xxe:vulnserver
      port: 8080
      args: ["/setup-aws-simulator.sh && catalina.sh run"]

  services:
    - name: attackerserver
      port: 8888
      targetPort: 8888

    - name: aws-metadata
      port: 8111
      targetPort: 8111

    - name: vulnserver
      port: 8080
      targetPort: 8080

  ingresses:
    - name: attackerserver
      port: 8888

    - name: aws-metadata
      port: 8111

    - name: vulnserver
      port: 8080
