xxe-lab:
  deployments:
    - name: attackerserver
      image: brightsec/java-xxe:attackerserver
      port: 8888
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 150m
          memory: 512Mi
      livenessProbe:
        httpGet:
          path: /
          port: 8888
          scheme: HTTP
        initialDelaySeconds: 120
        periodSeconds: 30

    - name: aws-metadata
      image: brightsec/java-xxe:aws-metadata
      port: 8111
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 150m
          memory: 512Mi
      livenessProbe:
        httpGet:
          path: /
          port: 8111
          scheme: HTTP
        initialDelaySeconds: 120
        periodSeconds: 30

    - name: vulnserver
      image: brightsec/java-xxe:vulnserver
      # entrypoint: ""
      port: 8080
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 150m
          memory: 512Mi
      livenessProbe:
        httpGet:
          path: /
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 120
        periodSeconds: 30

  services:
    - name: attackerserver
      port: 8888
      targetPort: 8888

    - name: aws-metadata
      port: 8111
      targetPort: 8111

    - name: vulnserver
      port: 8080
      targetPort: 8080

  ingresses:
    - name: attackerserver
      port: 8888

    - name: aws-metadata
      port: 8111

    - name: vulnserver
      port: 8080
