simple-service:
  application:
    image: "hightechsec/docker-dvwa"
    port: 80
    env:
      foo: bar
    resources:
      requests:
        cpu: 50m
        memory: 750Mi
        ephemeral-storage: "4Gi"
      limits:
        memory: 1024Mi
    livenessProbe:
      httpGet:
        path: /
        port: 80
        scheme: HTTP
      initialDelaySeconds: 120
      periodSeconds: 30
