simple-service:
  application:
    image: ghcr.io/neuralegion/stress_web
    port: 3000
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 512Mi
    livenessProbe:
      httpGet:
        path: /
        port: 3000
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 30
    startupProbe:
      httpGet:
        path: /
        port: 3000
        scheme: HTTP
