apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 9090
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: {{ .Release.Name }}
