{{- if .Values.ingress.url }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-ssl-protocols: "TLSv1.1 TLSv1.2"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: letsencrypt-cf-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.ingress.url }}
      secretName: {{ if eq .Values.ingress.cert "" }}{{ .Release.Name }}-first{{ else }}{{ .Values.ingress.cert }}{{ end }}
  rules:
    - host: {{ .Values.ingress.url }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: 8080
{{- end }}

{{- if .Values.ingress.url }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-second
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-ssl-protocols: "TLSv1.1 TLSv1.2"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: letsencrypt-cf-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - second.{{ .Values.ingress.url }}
      secretName: {{ if eq .Values.ingress.cert "" }}{{ .Release.Name }}-second{{ else }}{{ .Values.ingress.cert }}{{ end }}
  rules:
    - host: second.{{ .Values.ingress.url }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-second
                port:
                  number: 8000
{{- end }}
