apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-second
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
