apiVersion: v1
kind: Service
metadata:
  name: {{ include "crapi.fullname" . }}-{{ .Values.mailhog.webService.name }}
  namespace: {{ .Values.mailhog.namespace }}
  labels:
    release: {{ .Release.Name }}
    {{- with .Values.mailhog.webService.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ports:
  - name: web
    port: {{ .Values.mailhog.webPort }}
#    nodePort: {{ .Values.mailhog.webService.nodePort }}
    protocol: TCP
  selector:
    {{- toYaml .Values.mailhog.serviceSelectorLabels | nindent 4 }}
    release: {{ .Release.Name }}
  sessionAffinity: None
#  type: LoadBalancer
#  status:
#    loadBalancer: {}

