simple-service:
  application:
    image: anatol1988/chaotic-shop@sha256:9929b75ec9db598c73535a85bd598be755459e7cc68bc7ef8ac6eed66bc68a80
    port: 5001
    resources:
      requests:
        cpu: 0.4
        memory: 100Mi
      limits:
        memory: 200Mi
    livenessProbe:
      httpGet:
        path: /
        port: 5001
        scheme: HTTP
      initialDelaySeconds: 120
      periodSeconds: 30

global:
  repeaterIDs: null
  token: null
  cluster: null
  timeout: "30000"
  repeaterImageTag: null
