simple-service:
  application:
    image: ghcr.io/neuralegion/dynamic-link-server
    port: 3000
    livenessProbe:
      httpGet:
        path: /
        port: 3000
        scheme: HTTP
      initialDelaySeconds: 120
      periodSeconds: 30
