ingress:
  cert: "distributorwildcard"

application:
  image: "hightechsec/docker-dvwa"
  port: 80
  env: {}
  resources:
    requests:
      cpu: 50m
      memory: 500Mi
    limits:
      memory: 1024Mi

global:
  repeaterIDs: null
  token: null
  cluster: null
  timeout: "30000"
  repeaterImageTag: null
