apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: crapi
  name: {{ include "crapi.fullname" . }}-waitfor-grant
subjects:
- kind: ServiceAccount
  name: default
  namespace: crapi
  apiGroup: ""
subjects:
- kind: ServiceAccount
  name: system:serviceaccount:distributor:distributor
  namespace: distributor
roleRef:
  kind: ClusterRole
  name: {{ include "crapi.fullname" . }}-waitfor-reader
  apiGroup: ""
