simple-service:
  application:
    image: brightsec/ssti-ruby
    port: 6020
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 512Mi
    livenessProbe:
      httpGet:
        path: /
        port: 6020
        scheme: HTTP
      initialDelaySeconds: 120
      periodSeconds: 30

