apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-vulnserver
  labels:
    app: {{ $.Release.Name }}-vulnserver
data:
  setup-aws-simulator.sh: |
    #!/bin/bash

    echo "Start of the script!"

    # Use the environment variables directly in the script
    simulatorip=$(ping -c 1 $AWS_METADATA_SERVICE | awk -F'[()]' '/PING/{print $2}')
    attackerip=$(ping -c 1 $ATTACKER_SERVER_SERVICE | awk -F'[()]' '/PING/{print $2}')

    echo "simulator: $simulatorip"

    # save the container names before setting IP forwarding
    echo $simulatorip aws-metadata-simulator-jaxb >> /etc/hosts
    echo $attackerip attackerserver-jaxb >> /etc/hosts

    # The following will mess up Docker's container name resolution. Choose iptables-legacy if iptables --list shows a warning of iptables-legacy.
    iptables -t nat -I OUTPUT 1 -p tcp -d 169.254.169.254 --dport 80 -j DNAT --to-destination $simulatorip:8111
    #iptables-legacy -t nat -I OUTPUT 1 -p tcp -d 169.254.169.254 --dport 80 -j DNAT --to-destination $simulatorip:8111

    echo "End of script!"
