{{- range .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    app: {{ $.Release.Name }}-{{ .name }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
{{- end }}
