---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: {{ .Release.Name }}
    spec:
      restartPolicy: Always
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "vulnerableidp"
        - "vulnerablesp"
      containers:
        - name: vulnerableidp
          image: brightsec/vulnerablesamlapp:vulnerableidp
          imagePullPolicy: Always
          env:
            - name: IDP_HOST
              value: "idp-{{ .Values.ingress.url }}"
            - name: SP_HOST
              value: "{{ .Values.ingress.url }}"
            - name: USE_HTTPS
              value: "1"
            {{- if .Values.adminRole }}
            - name: ADMIN_ROLE
              value: {{ .Values.adminRole | quote }}
            {{- end }} 
          ports:
          - name: port80
            containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 30

        - name: vulnerablesp
          image: brightsec/vulnerablesamlapp:vulnerablesp
          imagePullPolicy: Always
          ports:
          - containerPort: 8000
          env:
            - name: SP_HOST
              value: "{{ .Values.ingress.url }}"
            - name: IDP_HOST
              value: "idp-{{ .Values.ingress.url }}"
            - name: USE_HTTPS
              value: "1"
            {{- if .Values.adminRole }}
            - name: ADMIN_ROLE
              value: {{ .Values.adminRole | quote }}
            {{- end }}  
          resources:
            requests:
              cpu: 25m
              memory: 256Mi
            limits:
              cpu: 100m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 30

