simple-service:
  application:
    image: brightsec/xvwa
    port: 80
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
    livenessProbe:
      httpGet:
        path: /
        port: 80
        scheme: HTTP
      initialDelaySeconds: 120
      periodSeconds: 30
