simple-service:
  application:
    image: tuxotron/xvwa
    port: 80
    resources:
      requests:
        cpu: 50m
        memory: 750Mi
      limits:
        memory: 1024Mi
        ephemeral-storage: "4Gi"
    livenessProbe:
      httpGet:
        path: /
        port: 80
        scheme: HTTP
      initialDelaySeconds: 120
      periodSeconds: 30
