apiVersion: v2
name: ssti-suite-javascript
description: ssti-suite-javascript app.
type: application
keywords:
- ssti-suite-javascript
version: 0.0.1
dependencies:
- name: simple-service
  version: 0.0.1
  repository: "file://../../simple-service"
