simple-service:
  application:
    image: brightsec/ssti-javascript
    port: 5063
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 512Mi
    livenessProbe:
      httpGet:
        path: /
        port: 5063
        scheme: HTTP
      initialDelaySeconds: 120
      periodSeconds: 30

