simple-service:
  application:
    image: commixproject/commix-testbed
    port: 80
    resources:
      requests:
        cpu: 1
        memory: 512Mi
      limits:
        memory: 4Gi
    livenessProbe:
      httpGet:
        path: /
        port: 80
        scheme: HTTP
      initialDelaySeconds: 120
      periodSeconds: 30

global:
  repeaterIDs: null
  token: null
  cluster: null
  timeout: "30000"
  repeaterImageTag: null
