---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "crapi.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    {{ if eq .Values.ingress.cert "" }}
    cert-manager.io/cluster-issuer: letsencrypt-cf-prod
    {{ end }}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.url }}
      secretName: {{ if eq .Values.ingress.cert "" }}{{ include "crapi.fullname" . }}-crapi-web-secret{{ else }}{{ .Values.ingress.cert }}{{ end }}
  rules:
    - host: {{ .Values.ingress.url }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "crapi.fullname" . }}-crapi-web
                port:
                  number: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "crapi.fullname" . }}-mailhog-web
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    {{ if eq .Values.ingress.cert "" }}
    cert-manager.io/cluster-issuer: letsencrypt-cf-prod
    {{ end }}
spec:
  tls:
    - hosts:
        - mailhog.{{ .Values.ingress.url }}
      secretName: {{ if eq .Values.ingress.cert "" }}{{ include "crapi.fullname" . }}-crapi-mailhog-web-secret{{ else }}{{ .Values.ingress.cert }}{{ end }}
  rules:
    - host: mailhog-{{ .Values.ingress.url }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "crapi.fullname" . }}-mailhog-web
                port:
                  number: 8025

