simple-service:
  application:
    image: brightsec/ssti-python-django
    port: 5003
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 512Mi
    livenessProbe:
      httpGet:
        path: /
        port: 5003
        scheme: HTTP
      initialDelaySeconds: 120
      periodSeconds: 30

