xxe-lab:
  deployments:
    - name: attackerserver
      image: brightsec/php-xxe:attackerserver
      port: 8888

    - name: aws-metadata
      image: brightsec/php-xxe:aws-metadata
      port: 8111

    - name: vulnserver
      image: brightsec/php-xxe:vulnserver
      port: 80
      args: ["/setup-aws-simulator.sh && /my_init"]

  services:
    - name: attackerserver
      port: 8888
      targetPort: 8888

    - name: aws-metadata
      port: 8111
      targetPort: 8111

    - name: vulnserver
      port: 80
      targetPort: 80

  ingresses:
    - name: attackerserver
      port: 8888

    - name: aws-metadata
      port: 8111

    - name: vulnserver
      port: 80
