application:
  image: brightsec/modelcontextprotocol
  imagePullPolicy: IfNotPresent
  command:
    - node
    - dist/index.js
    - streamableHttp
  port: 3001
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi
  livenessProbe:
    tcpSocket:
      port: 3001
    initialDelaySeconds: 20
    periodSeconds: 30
  readinessProbe:
    tcpSocket:
      port: 3001
    initialDelaySeconds: 5
    periodSeconds: 10

ingress:
  enabled: true
  cert: ""

imagePullSecrets: []
