# static-app-with-delay/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "static-app-with-delay.fullname" . }}-tls
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.crt  }}
  tls.key: {{ .Values.tls.key  }}
