{{- $repeaterIDs := (or (and (hasKey .Values "global") .Values.global.repeaterIDs) (compact (list .Values.repeaterID))) }}
{{- $token := (or (and (hasKey .Values "global") .Values.global.token) .Values.token) }}
{{- $cluster := (or (and (hasKey .Values "global") .Values.global.cluster) .Values.cluster) }}
{{- $timeout := (or (and (hasKey .Values "global") .Values.global.timeout) .Values.timeout "30000") }}
{{- $repeaterImageTag := (or (and (hasKey .Values "global") .Values.global.repeaterImageTag) .Values.repeaterImageTag "latest") }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webhooks-receiver.fullname" . }}
  labels:
    app: {{ include "webhooks-receiver.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "webhooks-receiver.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "webhooks-receiver.name" . }}
    spec:
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - "target.local"
      containers:
        - name: webhooks-receiver-app
          image: "{{ .Values.webhooksReceiverApp.image }}"
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /events
              port: 8080
              scheme: HTTP

        {{- if and $token $cluster }}
        {{- range $index, $repeaterID := $repeaterIDs }}
        - name: repeater-{{ $index }}
          image: brightsec/cli:{{ $repeaterImageTag }}
          command: ["bright-cli", "repeater"]
          args:
            - "--token=$(TOKEN)"
            - "--id=$(REPEATER_ID)"
            - "--cluster=$(CLUSTER)"
            - "--timeout=$(TIMEOUT)"
            - "--log-level=verbose"
          resources:
            requests:
              cpu: 200m
              memory: 100Mi
          env:
            - name: REPEATER_ID
              value: "{{ $repeaterID }}"
            - name: TOKEN
              value: "{{ $token }}"
            - name: CLUSTER
              value: "{{ $cluster }}"
            - name: TIMEOUT
              value: "{{ $timeout }}"
        {{- end }}
        {{- end }}
