# webhooks-receiver/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "webhooks-receiver.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{ include "webhooks-receiver.name" . }}
