simple-service:
  application:
    image: "brightsec/security-crawl-maze:latest"
    port: 8080
    env:
      foo: bar
    resources:
      requests:
        cpu: 50m
        memory: 250Mi
      limits:
        memory: 512Mi
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: 8080
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: 8080
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
