apiVersion: v2
name: juiceshop
description: |
  OWASP Juice Shop is probably the most modern and sophisticated insecure web
  application!
type: application
keywords:
- juiceshop
version: 0.0.8
dependencies:
- name: simple-service
  version: 0.3.0
  repository: "file://../../simple-service"
