simple-service:
  application:
    image: "bkimminich/juice-shop:v12.0.0"
    port: 3000
    env:
      foo: bar
    resources:
      requests:
        cpu: 50m
        memory: 750Mi
      limits:
        memory: 1024Mi
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: 3000
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: 3000
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
