simple-service:
  application:
    image: brightsec/vampi
    port: 5000
    env:
      - name: vulnerable
        value: "1"
      - name: RAND_SEED
        value: "42"
    resources:
      requests:
        cpu: 25m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 126Mi
    livenessProbe:
      httpGet:
        path: /
        port: 5000
        scheme: HTTP
      initialDelaySeconds: 120
      periodSeconds: 30
