---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-university
  namespace: {{ .Release.Namespace }}
  labels:
    app: university
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: university
    spec:
 #     containers:
        - name: {{ .Chart.Name }}
          image: busk3r/genericuniversity
          command: ["/bin/sh"]
          args:
            - -c
            - |
              service mysql start &&
              sleep 10 &&
              mysql -u root -p -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH caching_sha2_password BY 'password';" &&
              php /root/Generic-University/artisan serve --host 0.0.0.0
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 512Mi
