ingress:
  url: k3s.brokencrystals.nexploit.app
  cert: ""
  authlevel: "."
images:
  main: unstable
  client: unstable
repeaterImageTag: ""
repeaterID: ""
token: ""
cluster: ""
timeout: ""
snifferApiURL: ""
snifferApiKey: ""
snifferProjectID: ""
snifferNetworkInterface: ""
clusterConfigMap: "brokencrystals-config"
