simple-service:
  application:
    image: brightsec/static-site
    imagePullPolicy: Always
    port: 80
    resources:
      requests:
        cpu: 1
        memory: 512Mi
      limits:
        memory: 4Gi
    livenessProbe:
      httpGet:
        path: /
        port: 80
        scheme: HTTP
      initialDelaySeconds: 120
      periodSeconds: 30
