---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: {{ .Release.Name }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Chart.Name }}
          image: neuralegion/dvws-node
          ports:
          - containerPort: 80
          command: ["/bin/sh"]
          args:
            - -c
            - |
              /wait && 
              node startup_script.js && 
              npm start
          env:
            - name: WAIT_HOSTS
              value: "localhost:3306, localhost:27017"
            - name: WAIT_HOSTS_TIMEOUT
              value: "60"
            - name: SQL_LOCAL_CONN_URL
              value: "localhost"
            - name: MONGO_LOCAL_CONN_URL
              value: "mongodb://localhost:27017/node-dvws"  
          resources:
            requests:
              cpu: 25m
              memory: 128Mi
            limits:
              cpu: 150m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 30

        - name: {{ .Chart.Name }}-mysql
          image: mysql:5.7
          ports:
          - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "mysecretpassword"
          resources:
            requests:
              cpu: 25m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 512Mi
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 60
            periodSeconds: 30
 
        - name: {{ .Chart.Name }}-mongo
          image: mongo:4.0.4
          ports:
          - containerPort: 27017
          resources:
            requests:
              cpu: 25m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 126Mi
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 60
            periodSeconds: 30


