---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "brokencrystals.fullname" . }}-keycloak-postgres-prod
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "brokencrystals.fullname" . }}-keycloak-postgres-prod
spec:
  selector:
    matchLabels:
      app: {{ include "brokencrystals.fullname" . }}-keycloak-postgres-prod
  template:
    metadata:
      labels:
        app: {{ include "brokencrystals.fullname" . }}-keycloak-postgres-prod
    spec:
      containers:
        - name: {{ include "brokencrystals.fullname" . }}-keycloak-postgres-prod
          image: postgres:12.2-alpine
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 60
            periodSeconds: 30
          env:
            - name: POSTGRES_DB
              value: "keycloak"
            - name: POSTGRES_USER
              value: "keycloak"
            - name: POSTGRES_PASSWORD
              value: "password"
          resources:
            requests:
              cpu: 100m
              memory: 50Mi          
      restartPolicy: Always

---
kind: Service
apiVersion: v1
metadata:
  name: {{ include "brokencrystals.fullname" . }}-keycloak-postgres-prod-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ include "brokencrystals.fullname" . }}-keycloak-postgres-prod
  ports:
    - name: postgres-keycloak
      port: 5432
      protocol: TCP
      targetPort: 5432

