simple-service:
  application:
    image: brightsec/beebox:v5
    port: 80
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1024Mi
    livenessProbe:
      httpGet:
        path: /
        port: 80
        scheme: HTTP
      initialDelaySeconds: 120
      periodSeconds: 30
