simple-service:
  application:
    image: brightsec/beebox:v6
    port: 80
    resources:
      requests:
        cpu: 500m
        memory: 500Mi
      limits:
        memory: 1500Mi
    livenessProbe:
      httpGet:
        path: /
        port: 80
        scheme: HTTP
      initialDelaySeconds: 120
      periodSeconds: 30
