apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "simple.name" . }}
  namespace: {{.Release.Namespace}}
data:
  {{ if .Values.application.env }}
  {{- range $key, $val := .Values.application.env }}
  {{ $key }}: {{ $val }}
  {{- end}}
  {{ end }}