apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  {{- if .Values.application.env }}
  {{- range $key, $val := .Values.application.env }}
  {{ $key }}: "{{ $val }}"
  {{- end }}
  {{- end }}
  {{- if .Values.global.env }}
  {{- range $key, $val := .Values.global.env }}
  {{ $key }}: "{{ $val }}"
  {{- end }}
  {{- end }}
