---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simple.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "simple.name" . }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: {{ include "simple.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "simple.name" . }}
    spec:
      containers:
        - name: dwva-app
          image: {{ .Values.application.image }}
          envFrom:
          - configMapRef:
              name: {{ include "simple.name" . }}
          resources:
            requests:
              cpu: 256m
              memory: 750Mi
            limits:
              cpu: 1
              memory: 1024Mi              
          livenessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 30