simple-service:
  application:
    image: brightsec/vulhub-appweb
    port: 8080
    resources:
      requests:
        cpu: 125m
        memory: 256Mi
      limits:
        cpu: 250m
        memory: 512Mi
    livenessProbe:
      httpGet:
        path: /
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 120
      periodSeconds: 30
