name: Update Brokencrystals Image Tags

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-image-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Check for new Docker image tags
        id: check-tags
        run: |
          .github/scripts/check-tags.py --output-file $GITHUB_OUTPUT --chart-file charts/brokencrystals/Chart.yaml
        shell: bash

      - name: Debug workflow state
        if: always()
        run: |
          echo "update_needed: ${{ steps.check-tags.outputs.update_needed }}"
          echo "latest_tag: ${{ steps.check-tags.outputs.latest_tag }}"
          echo "current_tag: ${{ steps.check-tags.outputs.current_tag }}"
          echo "suggested_branch: ${{ steps.check-tags.outputs.suggested_branch }}"
          echo "current_chart_version: ${{ steps.check-tags.outputs.current_chart_version }}"
          echo "updated_chart_version: ${{ steps.check-tags.outputs.updated_chart_version }}"

      - name: Create Pull Request
        if: steps.check-tags.outputs.update_needed == 'true'
        id: create-pull-request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update BC image tag to ${{ steps.check-tags.outputs.latest_tag }} and chart to ${{ steps.check-tags.outputs.updated_chart_version }}"
          title: "[BC update] ✅ ${{ steps.check-tags.outputs.current_tag }} → ${{ steps.check-tags.outputs.latest_tag }} (Chart: ${{ steps.check-tags.outputs.current_chart_version }} → ${{ steps.check-tags.outputs.updated_chart_version }}) ✅"
          body: |
            This PR updates the brokencrystals Docker image tag and chart version.

            **Change Details:**
            ```diff
            # Docker image
            - ${{ steps.check-tags.outputs.current_tag }}
            + ${{ steps.check-tags.outputs.latest_tag }}

            # Chart version
            - ${{ steps.check-tags.outputs.current_chart_version }}
            + ${{ steps.check-tags.outputs.updated_chart_version }}
            ```

            This update was automatically generated by GitHub Actions.
          branch: ${{ steps.check-tags.outputs.suggested_branch }}
          base: main
          delete-branch: false

      - name: Enable Pull Request Automerge
        run: gh pr merge --auto --rebase ${{ steps.create-pull-request.outputs.pull-request-number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
