# Karpenter Provider OCI
#
# Copyright (c) 2026 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/

apiVersion: v1
kind: Service
metadata:
  name: {{ include "karpenter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karpenter.labels" . | nindent 4 }}
  {{- if or .Values.additionalAnnotations .Values.service.annotations }}
  annotations:
  {{- with .Values.additionalAnnotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.service.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: {{ .Values.controller.metrics.port }}
      targetPort: http-metrics
      protocol: TCP
  selector:
    {{- include "karpenter.selectorLabels" . | nindent 4 }}