---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vulnlab.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "vulnlab.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "vulnlab.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "vulnlab.fullname" . }}
    spec:
      containers:
        - name: vulnlab
          image: yavuzlar/vulnlab
          resources:
            requests:
              cpu: 256m
              memory: 750Mi
            limits:
              cpu: 1
              memory: 1024Mi
              ephemeral-storage: "4Gi"
          livenessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 30

---
kind: Service
apiVersion: v1
metadata:
  name: {{ include "vulnlab.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ include "vulnlab.fullname" . }}
  ports:
    - port: 80
    