apiVersion: v2
name: vulhub-tomcat
description: vulhub-tomcat app. https://github.com/vulhub/vulhub/tree/master/tomcat/CVE-2017-12615
type: application
keywords:
- vulhub-tomcat
version: 0.0.2
dependencies:
- name: simple-service
  version: 0.0.1
  repository: "file://../../simple-service"
