---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mariadb
  namespace: {{ .Release.Namespace }}
data:
  my.cnf: |-
    [mysqld]
    max_allowed_packet = 512M
    [client-server]
    socket = /run/mysqld/mysqld.sock
    !includedir /etc/mysql/mariadb.conf.d/
    !includedir /etc/mysql/conf.d/
