---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: brightsec/sqli-lab
          lifecycle:
            postStart:
              exec:
                command:
                  - "sh"
                  - "-c"
                  - |
                    sleep 20 && /usr/bin/curl http://localhost/sql-connections/setup-db.php 
          volumeMounts:
            - name: {{ .Release.Name }}-db-connection
              mountPath: /app/public/sql-connections/db-creds.inc
              subPath: db-creds.inc
              readOnly: true     
          env:
            - name: DB_HOST
              value: "{{ .Release.Name }}-db"
            - name: DB_NAME
              value: "security"
            - name: DB_USER
              value: "euiti"
            - name: DB_PASS
              value: "euiti2019"

            # Settings of php.ini
            - name: PHP_SHORT_OPEN_TAG
              value: "On"
            - name: PHP_ERROR_REPORTING
              value: "E_ALL"
            - name: PHP_DISPLAY_ERRORS
              value: "On"
            - name: PHP_HTML_ERRORS
              value: "On"
            - name: PHP_XDEBUG_ENABLED
              value: "true"  
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 30
      volumes:
        - name: {{ .Release.Name }}-db-connection
          configMap:
            name: {{ .Release.Name }}-db-connection
